---
title: "Comparison of Spatial Interpolation Methods for Air Pollution Prediction: `gstat` and `mgcv`"
description: |
  Understanding the association between pollution exposure and the deleterious effect on population health is a vital precursor for modelling. However, there has been less comparisons of spatial interpolations (SIs) for pollution predictions due to different assumptions and mathematical processes. In addition, SI has been provided in a coarse temporal scale which is difficult to understand the dynamics of exposure by mobility patterns and seasonal effects. This paper aims to compare spatial interpolation methods to predict air pollution at a finer temporal scale. 57 pollution stations around Seoul, S.Korea were collected for the comparison between Universal Kriging using `gstat` and Generalised Additive Model using `mgcv`, with additional weights on road layers as an effect of roadside pollution fields. Neither of the interpolation methods was noticeably superior to the other, but the sparse station data meant that only very smoothed large-scale fields could be recovered, which did not accurately represent the extremes observed at individual stations.
author:
  - name: Hyesop Shin
    affiliation: MRC/CSO Social and Public Health Sciences Unit, University of Glasgow, UK, G12 8TB
    affiliation_url: https://www.gla.ac.uk/schools/healthwellbeing/staff/hyesopshin/
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    number_sections: true
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction
Understanding the association between pollution exposure and population health has long been examined. As most of the urban areas tend to experience disastrous levels of pollution frequently (Deligiorgi and Philippopoulos, 2011; Cariolet et al., 2018), residents can be unconsciously exposed to air pollution and result in respiratory or cardiovascular ailments (Zhang and Batterman, 2013). To minimise further adverse health effects attributed to air pollution, it is helpful to gain the spatial and temporal distribution on a refined scale.


In many countries, air pollution data are regularly collected from the monitoring stations. However, because air quality varies widely even in a small distance, for example, between near the roadside and walking across the park, data reported from the stations are less likely to be accurate. Background stations only represent for one district and even worse the values differ remarkably to the values monitored at roadsides as the receptors are installed far from surface. To overcome these restrictions, many studies have attempted to apply spatial interpolation (SI) techniques to generate area-level estimates of air pollution that allows research to further compute the potential exposure across small geographical grids (Jerrett et al., 2001; Buzzelli and Jerrett, 2004; Li et al., 2012; Greater London Authority, 2017; Min et al., 2020). Despite the critiques of statistical models that inevitably neglect the contributions of the dispersion of the model, spatial interpolation has remained a popular method due to its advantages of a mathematically sound concept, quick implementation speed regardless of the spatial extent, and helpful software such as ArcGIS and programming packages in R.





